// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD433z8VCVnCzejm0RAmDvL7rs75TkUXgw',
    appId: '1:952247677247:web:a9d2be9407f8fad089638a',
    messagingSenderId: '952247677247',
    projectId: 'wtfood-firebase',
    authDomain: 'wtfood-firebase.firebaseapp.com',
    storageBucket: 'wtfood-firebase.firebasestorage.app',
    measurementId: 'G-16K76DP4FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUwWvfM04SOktU9-5AJCK4-hIJi_oguA',
    appId: '1:952247677247:android:c539051255cc4a8489638a',
    messagingSenderId: '952247677247',
    projectId: 'wtfood-firebase',
    storageBucket: 'wtfood-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0mpKsqr89Dt5vq-ShcX8FT26d1urPS8',
    appId: '1:952247677247:ios:deb277708cef799f89638a',
    messagingSenderId: '952247677247',
    projectId: 'wtfood-firebase',
    storageBucket: 'wtfood-firebase.firebasestorage.app',
    iosClientId: '952247677247-5cd5soprtnd7vgf24p16ls6j63a14dpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtfoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0mpKsqr89Dt5vq-ShcX8FT26d1urPS8',
    appId: '1:952247677247:ios:deb277708cef799f89638a',
    messagingSenderId: '952247677247',
    projectId: 'wtfood-firebase',
    storageBucket: 'wtfood-firebase.firebasestorage.app',
    iosClientId: '952247677247-5cd5soprtnd7vgf24p16ls6j63a14dpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtfoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD433z8VCVnCzejm0RAmDvL7rs75TkUXgw',
    appId: '1:952247677247:web:bd26d03315db0c5489638a',
    messagingSenderId: '952247677247',
    projectId: 'wtfood-firebase',
    authDomain: 'wtfood-firebase.firebaseapp.com',
    storageBucket: 'wtfood-firebase.firebasestorage.app',
    measurementId: 'G-YERM644FZR',
  );

}